######################################################################
# Automatically generated by qmake (3.0) Sun Apr 5 15:27:43 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = kmeanstriangleclustering
INCLUDEPATH += . \
               src/dev \
               src/dev/spaces \
               src/dev/commons \
               src/dev/exceptions \
               src/dev/distances \
               src/dev/tfidf \
               src/dev/algorithms \
               src/dev/pickers \
               src/dev/readers \
               src/dev/triangle \
               src/dev/ui \
               src/test/algorithms \
               src/test/commons \
               src/test/distances \
               src/test/pickers \
               src/test/readers

# Input
HEADERS += src/dev/KMeans.hpp \
           src/dev/kmeanstriangle.hpp \
           src/dev/main.hpp \
           src/dev/models.hpp \
           src/dev/ui_clusteringview.h \
           src/dev/algorithms/abstractalgorithm.h \
           src/dev/algorithms/kmeansalgorithm.h \
           src/dev/commons/abstractpoint.h \
           src/dev/commons/centersdata.h \
           src/dev/commons/densepoint.h \
           src/dev/commons/partitiondata.h \
           src/dev/commons/sparsepoint.h \
           src/dev/commons/utils.h \
           src/dev/distances/abstractdistance.h \
           src/dev/distances/cosinedistance.h \
           src/dev/distances/euclideandistance.h \
           src/dev/distances/hamiltondistance.h \
           src/dev/exceptions/badindex.h \
           src/dev/exceptions/notacenterpicker.h \
           src/dev/exceptions/notimplemented.h \
           src/dev/exceptions/notsparsepoint.h \
           src/dev/pickers/abstractcenterspicker.h \
           src/dev/pickers/randomcenterpicker.h \
           src/dev/pickers/sequentialcenterspicker.h \
           src/dev/readers/abstractdatareader.h \
           src/dev/readers/fulldatareader.h \
           src/dev/readers/normalizedformatdatareader.h \
           src/dev/spaces/abstractpointsspace.h \
           src/dev/spaces/normalizedpointsspace.h \
           src/dev/spaces/pointsspace.h \
           src/dev/tfidf/stemmedfileinmemoryparser.h \
           src/dev/triangle/abstractaccountingcontainer.h \
           src/dev/triangle/upperbounds.h \
           src/dev/ui/clusteringview.h \
           src/test/algorithms/kmeansalgorithmut.h \
           src/test/commons/centersdataut.h \
           src/test/commons/densepointut.h \
           src/test/commons/partitiondataut.h \
           src/test/commons/sparsepointut.h \
           src/test/commons/utilsut.h \
           src/test/distances/cosinedistanceut.h \
           src/test/distances/euclideandistanceut.h \
           src/test/distances/hamiltondistanceut.h \
           src/test/pickers/randomcenterpickerut.h \
           src/test/pickers/sequentialcenterspickerut.h \
           src/test/readers/readersut.h
FORMS += src/dev/ui/clusteringview.ui
SOURCES += src/dev/clustering.cpp \
           src/dev/KMeans.cpp \
           src/dev/kmeanstriangle.cpp \
           src/dev/main.cpp \
           src/dev/simpdist.cpp \
           src/dev/test.cpp \
           src/dev/algorithms/abstractalgorithm.cpp \
           src/dev/algorithms/kmeansalgorithm.cpp \
           src/dev/commons/abstractpoint.cpp \
           src/dev/commons/centersdata.cpp \
           src/dev/commons/densepoint.cpp \
           src/dev/commons/partitiondata.cpp \
           src/dev/commons/sparsepoint.cpp \
           src/dev/commons/utils.cpp \
           src/dev/distances/abstractdistance.cpp \
           src/dev/distances/cosinedistance.cpp \
           src/dev/distances/euclideandistance.cpp \
           src/dev/distances/hamiltondistance.cpp \
           src/dev/exceptions/badindex.cpp \
           src/dev/exceptions/notacenterpicker.cpp \
           src/dev/exceptions/notimplemented.cpp \
           src/dev/exceptions/notsparsepoint.cpp \
           src/dev/pickers/abstractcenterspicker.cpp \
           src/dev/pickers/randomcenterpicker.cpp \
           src/dev/pickers/sequentialcenterspicker.cpp \
           src/dev/readers/abstractdatareader.cpp \
           src/dev/readers/fulldatareader.cpp \
           src/dev/readers/normalizedformatdatareader.cpp \
           src/dev/spaces/abstractpointsspace.cpp \
           src/dev/spaces/normalizedpointsspace.cpp \
           src/dev/spaces/pointsspace.cpp \
           src/dev/tfidf/stemmedfileinmemoryparser.cpp \
           src/dev/triangle/abstractaccountingcontainer.cpp \
           src/dev/triangle/upperbounds.cpp \
           src/dev/ui/clusteringview.cpp \
           src/test/algorithms/kmeansalgorithmut.cpp \
           src/test/commons/centersdataut.cpp \
           src/test/commons/densepointut.cpp \
           src/test/commons/partitiondataut.cpp \
           src/test/commons/sparsepointut.cpp \
           src/test/commons/utilsut.cpp \
           src/test/distances/cosinedistanceut.cpp \
           src/test/distances/euclideandistanceut.cpp \
           src/test/distances/hamiltondistanceut.cpp \
           src/test/pickers/randomcenterpickerut.cpp \
           src/test/pickers/sequentialcenterspickerut.cpp \
           src/test/readers/readersut.cpp
