######################################################################
# Automatically generated by qmake (3.0) Sun Apr 5 15:50:21 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = commons
INCLUDEPATH += .

# Input
HEADERS += centersdataut.h \
           densepointut.h \
           partitiondataut.h \
           sparsepointut.h \
           utilsut.h
SOURCES += centersdataut.cpp \
           densepointut.cpp \
           partitiondataut.cpp \
           sparsepointut.cpp \
           utilsut.cpp


#rest of the config
CONFIG += c++11
QMAKE_CXXFLAGS += -std=c++11
INCLUDEPATH += ../../dev/
