######################################################################
# Automatically generated by qmake (3.0) Mon Feb 16 13:26:58 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += kmeansalgorithmut.h
SOURCES += kmeansalgorithmut.cpp
