######################################################################
# Automatically generated by qmake (3.0) Sun Apr 5 15:50:21 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = pickers
INCLUDEPATH += .

# Input
HEADERS += randomcenterpickerut.h sequentialcenterspickerut.h
SOURCES += randomcenterpickerut.cpp sequentialcenterspickerut.cpp


#rest of the config
CONFIG += c++11
QMAKE_CXXFLAGS += -std=c++11
INCLUDEPATH += ../../dev/
