######################################################################
# Automatically generated by qmake (3.0) Mon Feb 16 13:27:15 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += fulldatareaderut.h normalizedformatdatareaderut.h
SOURCES += fulldatareaderut.cpp normalizedformatdatareaderut.cpp
