######################################################################
# Automatically generated by qmake (3.0) Mon Feb 16 13:27:12 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += randomcenterpickerut.h sequentialcenterspickerut.h
SOURCES += randomcenterpickerut.cpp sequentialcenterspickerut.cpp
