######################################################################
# Automatically generated by qmake (3.0) Mon Feb 16 13:27:02 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += centersdataut.h \
           densepointut.h \
           partitiondataut.h \
           sparsepointut.h \
           utilsut.h
SOURCES += centersdataut.cpp \
           densepointut.cpp \
           partitiondataut.cpp \
           sparsepointut.cpp \
           utilsut.cpp
