######################################################################
# Automatically generated by qmake (3.0) Sun Apr 5 15:50:21 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = readers
INCLUDEPATH += .

# Input
HEADERS += readersut.h
SOURCES += readersut.cpp


#rest of the config
CONFIG += c++11
QMAKE_CXXFLAGS += -std=c++11
INCLUDEPATH += ../../dev/
