######################################################################
# Automatically generated by qmake (3.0) Mon Feb 16 13:27:08 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += cosinedistanceut.h euclideandistanceut.h hamiltondistanceut.h
SOURCES += cosinedistanceut.cpp euclideandistanceut.cpp hamiltondistanceut.cpp
